:PROPERTIES:
:ID:       8e6396ed-1c65-425a-b451-eca706d53e90
:ROAM_REFS: https://leetcode.com/problems/string-to-integer-atoi/
:END:
#+title: 8. String to Integer (atoi)
#+filetags: :Medium:

* [[id:2b2e3e1f-924b-43fe-a7f8-a1eb6482d2f2][问题]]
Implement the ~myAtoi(string s)~ function, which converts a string to a 32-bit signed integer (similar to C/C++'s ~atoi~ function).

The algorithm for ~myAtoi(string s)~ is as follows:

- Read in and ignore any leading whitespace.
- Check if the next character (if not already at the end of the string) is ~'-'~ or ~'+'~. Read this character in if it is either. This determines if the final result is negative or positive respectively. Assume the result is positive if neither is present.
- Read in next the characters until the next non-digit character or the end of the input is reached. The rest of the string is ignored.
- Convert these digits into an integer (i.e. ~"123" -> 123~, ~"0032" -> 32~). If no digits were read, then the integer is ~0~. Change the sign as necessary (from step 2).
- If the integer is out of the 32-bit signed integer range ~[-2^{31}, 2^{31} - 1]~, then clamp the integer so that it remains in the range. Specifically, integers less than ~-2^{31}~ should be clamped to ~-2^{31}~, and integers greater than ~2^{31} - 1~ should be clamped to ~2^{31} - 1~.
- Return the integer as the final result.

*Note:*

- Only the space character ~' '~ is considered a whitespace character.
- *Do not ignore* any characters other than the leading whitespace or the rest of the string after the digits.

*Example 1:*

#+BEGIN_SRC
Input: s = "42"
Output: 42
Explanation: The underlined characters are what is read in, the caret is the current reader position.
Step 1: "42" (no characters read because there is no leading whitespace)
         ^
Step 2: "42" (no characters read because there is neither a '-' nor '+')
         ^
Step 3: "_42_" ("42" is read in)
           ^
The parsed integer is 42.
Since 42 is in the range [-2^{31}, 2^{31} - 1], the final result is 42.
#+END_SRC

Example 2:

#+BEGIN_SRC
Input: s = "   -42"
Output: -42
Explanation:
Step 1: "_   _-42" (leading whitespace is read and ignored)
            ^
Step 2: "   _-_42" ('-' is read, so the result should be negative)
             ^
Step 3: "   -_42_" ("42" is read in)
               ^
The parsed integer is -42.
Since -42 is in the range [-2^{31}, 2^{31} - 1], the final result is -42.
#+END_SRC

Example 3:

#+BEGIN_SRC
Input: s = "4193 with words"
Output: 4193
Explanation:
Step 1: "4193 with words" (no characters read because there is no leading whitespace)
         ^
Step 2: "4193 with words" (no characters read because there is neither a '-' nor '+')
         ^
Step 3: "_4193_ with words" ("4193" is read in; reading stops because the next character is a non-digit)
             ^
The parsed integer is 4193.
Since 4193 is in the range [-2^{31}, 2^{31} - 1], the final result is 4193.
#+END_SRC

*Constraints:*

- ~0 <= s.length <= 200~
- ~s~ consists of English letters (lower-case and upper-case), digits (~0-9~), ~' '~, ~'+'~, ~'-'~, and ~'.'~.

* 思路
本题题意本身并不复杂, 复杂的是边界条件如何设置:

- 在数字以前只能有空格以及正负号 ~" ", "+", "-"~, 否则返回 =0=
- 在数字后遇到任意不是数字的符号直接返回
- 数字不能超出 ~32-bit~ 位数字的范围
- 数字的正负号需要添加

** 数字前的符号
此处使用 ~flag~ 这一标志位来判断, 默认为 =false=, 遇到数字设为 =true=
遇到数字前只能为空格和正负号, 否则退出循环

** 数字后的符号
遇到数字后再遇到不是数字的字符, 直接退出循环

** 数字超出范围
结果每次变化后进行判断

** 数字符号
符号 ~sign~ 默认为 1, 通过 ~sign = 44 - int(c)~ 设置具体符号, 并在结果变化时相乘

* 代码
#+BEGIN_SRC go
func myAtoi(s string) int {
    res := 0
    flag := false
    sign := 1
    for _, c := range s {
        if !flag && c == 32 { // white space
            continue
        } else if !flag && (c == 43 || c == 45) {
            flag = true
            sign = 44 - int(c) // 43: +, 45: -
        } else if c >= 48 && c <= 57 { // '0' <= c <= '9'
            flag = true
            res = res * 10 + (int(c) - 48) * sign
            if res < -2147483648 {
                res = -2147483648
                break
            } else if res > 2147483647 {
                res = 2147483647
                break
            }
        } else {
            break
        }
    }
    return res
}
#+END_SRC
